### ISSUE TITLE
Compilation fatal error: io.h

### ISSUE THREAD

**Issue by papiche** [thomasarmel/uqload_downloader#1]
```
make uqload_downloader
g++     uqload_downloader.cpp   -o uqload_downloader
In file included from uqload_downloader.cpp:3:0:
Downloader.h:5:10: fatal error: io.h: Aucun fichier ou dossier de ce type
```

**Comment by papiche** [comment]
could you help me to make a howto compile documentation?

**Comment by thomasarmel** [comment]
Hello,
The include file io.h is not a part of the SL, it only belongs to the Windows toolkit if I remember well.
But it's only used for the code "**if (_access(m_outputFile.c_str(), 0) == 0)**" (verify if the file already exists).
I know I should have generified the code before making it public.
So you could verify if the code is compiled in a VS environment, in this case use <io.h> and _access(). Otherwise, <unistd.h> and access().
Thanks for your tip-off by the way^^

**Comment by thomasarmel** [comment]
Ok I've done the code compile on Linux right now.

**Comment by thomasarmel** [comment]
To compile you just need libcurl (with TLS support of course) and the C++ SL.
Run **g++ -o uqload_downloader uqload_downloader.cpp Downloader.cpp -lcurl**
and **./uqload_downloader.exe https://uqload.com/embed-[...].html yourmovie.mp4**

**Comment by papiche** [comment]
Thanks for your tips. I was still having io.h error until I found this solution.
```sudo cp /usr/include/x86_64-linux-gnu/sys/io.h /usr/include```

But then, another error arise.

```
uqload_downloader.cpp: In function ‘int main(int, char**)’:
uqload_downloader.cpp:18:52: error: invalid conversion from ‘int (*)(void*, curl_off_t, curl_off_t, curl_off_t, curl_off_t) {aka int (*)(void*, long int, long int, long int, long int)}’ to ‘void*’ [-fpermissive]
  uqDownloader->setDownloadCallback(downloadCallback);
                                                    ^
In file included from uqload_downloader.cpp:3:0:
Downloader.h:16:7: note:   initializing argument 1 of ‘void Downloader::setDownloadCallback(void*)’
  void setDownloadCallback(void* callback);
       ^~~~~~~~~~~~~~~~~~~
In file included from Downloader.h:6:0,
                 from Downloader.cpp:1:
Downloader.cpp: In member function ‘void Downloader::setDownloadCallback(void*)’:
Downloader.cpp:38:48: error: ‘FALSE’ was not declared in this scope
   curl_easy_setopt(m_curl, CURLOPT_NOPROGRESS, FALSE);
                                                ^
Downloader.cpp:38:48: note: suggested alternative: ‘FILE’
Downloader.cpp: In member function ‘void Downloader::download()’:
Downloader.cpp:72:6: error: ‘_access’ was not declared in this scope
  if (_access(m_outputFile.c_str(), 0) == 0)
      ^~~~~~~
Downloader.cpp:72:6: note: suggested alternative: ‘accept’
  if (_access(m_outputFile.c_str(), 0) == 0)
      ^~~~~~~
      accept
Downloader.cpp:76:2: error: ‘fopen_s’ was not declared in this scope
  fopen_s(&m_fp, m_outputFile.c_str(), "wb");
  ^~~~~~~
Downloader.cpp:76:2: note: suggested alternative: ‘fopen64’
  fopen_s(&m_fp, m_outputFile.c_str(), "wb");
  ^~~~~~~
  fopen64
```
I would like to find a solution without installing "Windows toolkit", I don't like dealing with this company.

**Comment by thomasarmel** [comment]
yes of course please pull again (I've made some changes in my code)

**Comment by thomasarmel** [comment]
And you won't have to install any windows toolkit anymore

**Comment by papiche** [comment]
GREAT all is fine !

**Comment by thomasarmel** [comment]
Ok I'll close the issue.
Thanks for your feedback ;)
