### ISSUE TITLE
Question about implementation

### ISSUE THREAD

**Issue by ValentinFrancois** [thomasarmel/uqload_downloader#10]
Hi,
thanks for this download util, it works like a charm!

I'm considering making a uqload video downloader browser extension, and looking at your code:
Do I understand correctly that the main trick to bypass the `error_wrong_ip` response when requesting the .mp4, is to set the referer URL to its corresponding `https://uqload.co/embed-xxxxxxxx.html` page?

**Comment by thomasarmel** [comment]
Hi,
Yes you're right, the `error_wrong_ip` is misleading, as the server only checks that **HTTP Referer header** corresponds to `https://uqload.co/embed-xxxxxxxx.html`.
Good luck for your implementation :)

(and btw don't hesitate if you want I can refer it in this repo README)
