### ISSUE TITLE
C# Project

### ISSUE THREAD

**Issue by gameplayoffert** [thomasarmel/uqload_downloader#4]
Hi, i want to do the same thing in C# but i don't understand what you do with the url. I have a question the "embed" is the url ? or you need to merge it with the ".mp4" ? because i don't understand.

**Comment by gameplayoffert** [comment]
Alors je reposte un autre message puisque je n'avais pas remarquer que vous étiez français désolé. Alors je cherche à faire la même chose mais en C# le seul problème c'est que je ne comprends pas quelle est la bonne url. Faut-il envoyer une requête au serveur pour avoir une autre url en retour ?

**Comment by gameplayoffert** [comment]
Non c'est bon j'ai un peux lus ton code "C++" et j'ai compris tu utilise l'url .mp4 en tant que "Url" et le reste en tant que "Referer" et j'ai tester et cela fonctionne. Je vais probablement publier la source sur "Github" cela ne te dérange pas ?

**Comment by thomasarmel** [comment]
Salut,
Oui du coup je suis français pas de souci :) .
Donc oui en fait l'astuce consiste juste à changer le Referer, j'ai passé une soirée entière à essayer de modifier tous les cookies possibles et imaginables pour découvrir qu'en réalité c'était juste ça...
Alors clairement non ça me dérange pas bien au contraire. Et d'ailleurs je pourrais aussi mettre un lien vers ton repo dans mon README si tu veux.
Après sinon je peux te proposer autre chose: tu forkes mon projet et tu rajoutes le tien dedans avec une PR (on fait par ex un dossier "cpp" et un autre "cs"). A toi de voir ;)

**Comment by gameplayoffert** [comment]
alors voila pour l'instant j'ai mis ton "uqload_downloader" en lien sur ma "repo".

Ma repo : https://github.com/gameplayoffert/UqloadDownloader

**Comment by thomasarmel** [comment]
Ok ça marche ravi d'avoir pu t'être utile :)
