### ISSUE TITLE
Error ubuntu g++

### ISSUE THREAD

**Issue by ambroiselebs** [thomasarmel/uqload_downloader#5]
Hello, I get this error on ubuntu : 

`Extract uqload links from ~/.kodi/temp/kodi.log
g++: error: uqload_downloader.cpp: Aucun fichier ou dossier de ce type
g++: error: Downloader.cpp: Aucun fichier ou dossier de ce type
INSTALL FAILED, 'sudo apt-get install libcurl4-openssl-dev -y' TRY AGAIN.
`

**Comment by thomasarmel** [comment]
Hello,
Did you try to compile the GUI application ? There is no Makefile for this version yet, you have to compile it manually.
In fact I could add the Makefile if needed :)

**Comment by thomasarmel** [comment]
If you want to compile the CLI version just follow this tutorial: https://github.com/thomasarmel/uqload_downloader/blob/main/cli/README.md .

**Comment by ambroiselebs** [comment]
Ok thanks you so much !

**Comment by thomasarmel** [comment]
Has your issue been solved ?

**Comment by ambroiselebs** [comment]
> Is your issue solved ?

yes thanks you
