### ISSUE TITLE
How to Install (WSL2)

### ISSUE THREAD

**Issue by koitaki** [thomasarmel/uqload_downloader#8]
Thomas,
This tool looks good, thanks for creating it, but couldn't work out how to install on Windows (or WSL2).
So had to give up and go try youtube-dl...where I found find another world of problems.
So if you see this and provide a pointer, I'll have another crack at it.
Thanks!

**Comment by thomasarmel** [comment]
Hello,
on Windows it's pretty easy: just download the archive containing the GUI and the CLI version and execute ont of them: https://github.com/thomasarmel/uqload_downloader/releases/download/v2.0/uqload_downloader_cli_gui_win64.zip .
On WSL just follow the instructions on the README: https://github.com/thomasarmel/uqload_downloader/tree/main/cli
