### ISSUE TITLE
Error 32

### ISSUE THREAD

**Issue by L-Dlbcq** [thomasarmel/uqload_downloader#9]
Every time i try to use the app, i've got an error 32. This error said the file i try to download is already in use by other process

How to solve this ?

**Comment by thomasarmel** [comment]
Hello,
Do you use GUI or CLI version? On which operating system?
Can you provide me a screenshot?

**Comment by MightyTea** [comment]
i have the same problem, 
![image](https://user-images.githubusercontent.com/32665892/169605346-daf13d90-c08d-4eb8-b7ce-f43d985d1094.png)

**Comment by thomasarmel** [comment]
And the file didn't exit before?
Do you have the right permissions on the directory **C:\Users\video\Desktop**?

**Comment by MightyTea** [comment]
yes it didn't exit and yes

**Comment by MightyTea** [comment]
ok i found the issue and the solution, it gives this error when the link is invalid, in my case, it was a .ORG link but it has to be a .COM, because once u click the share button on uqload, it gives u automatically a .ORG link.
So all u have to do is replacing the .org by .com in the link

**Comment by thomasarmel** [comment]
Ok, so that's a very irrelevant error message.

**Comment by L-Dlbcq** [comment]
Sorry but problem still here for me.

**Comment by thomasarmel** [comment]
@L-Dlbcq please could you share a screenshot, or the URL you entered?

**Comment by L-Dlbcq** [comment]
So i made a new test and everything seems okay. The problem is now solved. I think it's because i use this type of link https://uqload.com/embed-ioy6thjqxv2l.html and not a embed link.
